### ISSUE TITLE
New experts can select deleted/deactivated institutions.

### ISSUE THREAD

**Issue by MarkVanCrombrugge** [IODEOostende/oeissues#12] opened 2017-08-07 13:18 UTC
### Actual behaviour
When a new user wants to select an institution, the list contains all institutions (active, deactivated and deleted ones) so it’s impossible to see which institution is the active one and which ones are not to be used.

Same goes for an existing expert who needs to change her/his institution.

To make it useable for myself during the cleaning up, I put a “†”as last character of the name if the institution is deleted or deactivated but it would be logical to only display valid institutions. 

In the following popup list, only one institution is correct...
![institutions](https://user-images.githubusercontent.com/30799556/29028023-44d4afb8-7b83-11e7-8994-c51463851e09.png)

Comment (Mithun): Pending. 

### Steps to reproduce

1.
2.
3.

### Context

- Operating system: macOS/Windows/Linux/iOS/Android
- Operating system version:
- Browser: Chrome/Safari/Firefox/Edge/Internet Explorer
- Browser version:

**Comment by AdiKakodkar** [comment] 2017-08-18 11:26
Duplicate of #28

**Closed by AdiKakodkar** 2017-08-18 11:26 UTC
